numpy

In [7]:
import numpy


In [8]:
2+3

5

In [11]:
import numpy as np

In [22]:
a= [1,2,3,4]
b=np.array([[1,2,3,4],[1,0,4,4]])

In [23]:
b.shape

(2, 4)

In [14]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
np.arange(0,29,5)

array([ 2,  7, 12, 17, 22, 27])

alfan sukmana praja
(5,7)
[[0,5,10,15,20,25,30,35],[0,5,10,15,20,25,30,35],[0,5,10,15,20,25,30,35],[0,5,10,15,20,25,30,35],[0,5,10,15,20,25,30,35]]


In [29]:
nama_1="jaka"
nama_2='saputra'
nama_3='wahyu'
dimensi_1 = len(nama_1)
dimensi_2 = len(nama_2)
step_for_array=len(nama_3)
z=np.arange(0,step_for_array*dimensi_2,step_for_array)
array_placeholder=np.array([])
for i in range(dimensi_1):
    array_placeholder=np.append(array_placeholder,z)

In [30]:
print(array_placeholder)

[ 0.  5. 10. 15. 20. 25. 30.  0.  5. 10. 15. 20. 25. 30.  0.  5. 10. 15.
 20. 25. 30.  0.  5. 10. 15. 20. 25. 30.]


In [47]:
arr1 =np.array([[1,2,3,4],[5,6,7,8]])
arr2 =np.array([[9,10],[11,12],[13,14],[15,16]])
arr3 =np.array([[15,16,17,18]])

In [38]:
arr5 = np.vstack((arr1,arr2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

In [43]:
a=arr1[(arr1>=0)]

In [44]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
b=arr2[(arr2>=0)]

In [49]:
b

array([ 9, 10, 11, 12, 13, 14, 15, 16])

In [54]:
np.hsplit(arr2,2)

[array([[ 9],
        [11],
        [13],
        [15]]),
 array([[10],
        [12],
        [14],
        [16]])]

In [61]:
import numpy as np
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/ardhiraka/PFDS_sources/master/nbaallelo.csv')

In [58]:
df = pd.read_csv('https://raw.githubusercontent.com/ardhiraka/PFDS_sources/master/nbaallelo.csv')

NameError: name 'pd' is not defined

In [62]:
len(df)

126314

In [63]:
df.head()

gameorder       game_id lg_id  _iscopy  year_id  date_game  seasongame  \
0          1  194611010TRH   NBA        0     1947  11/1/1946           1   
1          1  194611010TRH   NBA        1     1947  11/1/1946           1   
2          2  194611020CHS   NBA        0     1947  11/2/1946           1   
3          2  194611020CHS   NBA        1     1947  11/2/1946           2   
4          3  194611020DTF   NBA        0     1947  11/2/1946           1   

   is_playoffs team_id  fran_id  ...  win_equiv  opp_id  opp_fran  opp_pts  \
0            0     TRH  Huskies  ...  40.294830     NYK    Knicks       68   
1            0     NYK   Knicks  ...  41.705170     TRH   Huskies       66   
2            0     CHS    Stags  ...  42.012257     NYK    Knicks       47   
3            0     NYK   Knicks  ...  40.692783     CHS     Stags       63   
4            0     DTF  Falcons  ...  38.864048     WSC  Capitols       50   

   opp_elo_i  opp_elo_n  game_location  game_result  forecast notes  
0  1300.0000  1306.7233              H            L  0.640065   NaN  
1  1300.0000  1293.2767              A            W  0.359935   NaN  
2  1306.7233  1297.0712              H            W  0.631101   NaN  
3  1300.0000  1309.6521              A            L  0.368899   NaN  
4  1300.0000  1320.3811              H            L  0.640065   NaN  

[5 rows x 23 columns]

In [67]:
df.describe

<bound method NDFrame.describe of         gameorder       game_id lg_id  _iscopy  year_id  date_game  \
0               1  194611010TRH   NBA        0     1947  11/1/1946   
1               1  194611010TRH   NBA        1     1947  11/1/1946   
2               2  194611020CHS   NBA        0     1947  11/2/1946   
3               2  194611020CHS   NBA        1     1947  11/2/1946   
4               3  194611020DTF   NBA        0     1947  11/2/1946   
...           ...           ...   ...      ...      ...        ...   
126309      63155  201506110CLE   NBA        0     2015  6/11/2015   
126310      63156  201506140GSW   NBA        0     2015  6/14/2015   
126311      63156  201506140GSW   NBA        1     2015  6/14/2015   
126312      63157  201506170CLE   NBA        0     2015  6/16/2015   
126313      63157  201506170CLE   NBA        1     2015  6/16/2015   

        seasongame  is_playoffs team_id    fran_id  ...  win_equiv  opp_id  \
0                1            0     TRH    Husk

In [89]:
exams_data_df=pd.read_csv('./exams.csv')

In [90]:
exams_data_df.head(10)

gender race/ethnicity parental level of education         lunch  \
0  female        group B            some high school      standard   
1    male        group B            some high school      standard   
2  female        group B          associate's degree      standard   
3  female        group C            some high school  free/reduced   
4    male        group D            some high school      standard   
5    male        group E            some high school      standard   
6    male        group B          associate's degree      standard   
7  female        group B          associate's degree      standard   
8  female        group B           bachelor's degree      standard   
9    male        group D                some college  free/reduced   

  test preparation course  math score  reading score  writing score  
0               completed          56             65             64  
1                    none          65             54             54  
2               completed          81             85             82  
3               completed          48             70             70  
4                    none          78             66             69  
5               completed          79             71             71  
6                    none          70             65             61  
7               completed          61             78             81  
8                    none          69             80             77  
9                    none          43             50             53

In [72]:
exams_data_df.tail(10)

gender race/ethnicity parental level of education         lunch  \
90    male        group A                some college      standard   
91  female        group D           bachelor's degree      standard   
92  female        group D          associate's degree  free/reduced   
93    male        group B            some high school  free/reduced   
94    male        group B                some college      standard   
95    male        group E            some high school      standard   
96    male        group E                some college      standard   
97  female        group C            some high school  free/reduced   
98    male        group C                 high school      standard   
99  female        group B          associate's degree  free/reduced   

   test preparation course  math score  reading score  writing score  
90                    none          70             63             59  
91                    none          83             86             96  
92                    none          62             76             72  
93                    none          54             53             52  
94                    none          45             34             37  
95               completed          59             58             54  
96               completed          66             69             64  
97                    none          49             59             59  
98                    none          63             55             54  
99                    none          53             63             61

In [73]:
exams_data_df

gender race/ethnicity parental level of education         lunch  \
0   female        group B            some high school      standard   
1     male        group B            some high school      standard   
2   female        group B          associate's degree      standard   
3   female        group C            some high school  free/reduced   
4     male        group D            some high school      standard   
..     ...            ...                         ...           ...   
95    male        group E            some high school      standard   
96    male        group E                some college      standard   
97  female        group C            some high school  free/reduced   
98    male        group C                 high school      standard   
99  female        group B          associate's degree  free/reduced   

   test preparation course  math score  reading score  writing score  
0                completed          56             65             64  
1                     none          65             54             54  
2                completed          81             85             82  
3                completed          48             70             70  
4                     none          78             66             69  
..                     ...         ...            ...            ...  
95               completed          59             58             54  
96               completed          66             69             64  
97                    none          49             59             59  
98                    none          63             55             54  
99                    none          53             63             61  

[100 rows x 8 columns]

In [74]:
exams_data_df.info

<bound method DataFrame.info of     gender race/ethnicity parental level of education         lunch  \
0   female        group B            some high school      standard   
1     male        group B            some high school      standard   
2   female        group B          associate's degree      standard   
3   female        group C            some high school  free/reduced   
4     male        group D            some high school      standard   
..     ...            ...                         ...           ...   
95    male        group E            some high school      standard   
96    male        group E                some college      standard   
97  female        group C            some high school  free/reduced   
98    male        group C                 high school      standard   
99  female        group B          associate's degree  free/reduced   

   test preparation course  math score  reading score  writing score  
0                completed          56      

In [75]:
exams_data_df.shape

(100, 8)

In [76]:
len(exams_data_df)

100

In [77]:
exams_data_df.describe

<bound method NDFrame.describe of     gender race/ethnicity parental level of education         lunch  \
0   female        group B            some high school      standard   
1     male        group B            some high school      standard   
2   female        group B          associate's degree      standard   
3   female        group C            some high school  free/reduced   
4     male        group D            some high school      standard   
..     ...            ...                         ...           ...   
95    male        group E            some high school      standard   
96    male        group E                some college      standard   
97  female        group C            some high school  free/reduced   
98    male        group C                 high school      standard   
99  female        group B          associate's degree  free/reduced   

   test preparation course  math score  reading score  writing score  
0                completed          56    

In [86]:
exams_data_index=exams_data_df.set_index('gender')

In [88]:
exams_data_index.axes[1]

Index(['race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')